### ISSUE TITLE
Url Fragment

### ISSUE THREAD

**Issue by webfolderio** [Stiffstream/restinio#11]
Hi,

Browsers won't send the URL fragment but there is __fragment()__ method in __restinio::http_request_header_t__ struct.

As far as i know, Java servlet or similar libraries does not have a such method.

What is the use case of this method?

Thanks

**Comment by eao197** [comment]
Hi!

The fragment part of URL is interpreted by browser by itself, because of it a browser or an utility like *curl* strips this part of URL issuing a request to a server. But HTTP-request can also be issued from an application via a library like *libcurl* (or even via some hand-written code). In such cases URL in HTTP-request can contain fragment part. And `fragment()` method will return non-empty value in that case.

**Comment by webfolderio** [comment]
Thank you for the detailed and informative answer.
