### ISSUE TITLE
Question: stop processing on client closing connection 

### ISSUE THREAD

**Issue by bigerl** [Stiffstream/restinio#136]
I receive queries that might result in heavy workload via a restinio. The result is streamed to the client as it is calculated. 

It happens that a client closes the connection before it received the whole result. But the server isn't aware of that and goes on processing until the query is solved. 

I would like to know in the `request_handler` to avoid unnecessary server load. I assume I need to use a `connection_state_listener` that tells me when the connection is closed. 

But what I could not figure out is: How can I access that information inside the right `request_handler` exection?

**Comment by eao197** [comment]
Hi!

> How can I access that information inside the right request_handler execution?

`request_handle` that is passed by RESTinio to a request_handler doesn't expose any connection-related information to RESTinio's user. So the only way to share info between the `connection_state_listener` and a request_handler is to create some shared state in your application: the `connection_state_listener` will update that state and a request_handler will read it.

But there is another side: what does it mean to "heavy workload"? If your request_handler has to work long (for example the request handler can take several seconds or even several minutes) then you have to consider an approach with the delegation of the actual request processing to some worker thread (or thread pool). In that case, RESTinio will call your request_handler in the context of some RESTinio's thread. The request_handler delegates actual request processing to some other worker thread and returns `request_accepted`. In that case, RESTinio can serve other requests or checks for I/O activity (including the disconnection of the client).

Otherwise, if your request_handler does all the work in the context of RESTinio's thread then it can lead to the case when all RESTinio's threads are busy because request_handlers are called on them. And RESTinio will lose the ability to handle other I/O activities until some request_handler finishes its work.

**Comment by bigerl** [comment]
Thank you very much for the quick and comprehensive answer. It was really helpful and covered a lot if questionmarks I was not even aware if. I have now an idea how I need to rewrite my request handling.

**Comment by eao197** [comment]
Hope this information can be useful too:

* a brief explanation of "threading model" and distinguishing between sync and async request handling: https://github.com/Stiffstream/restinio/issues/133#issuecomment-737837845
* an example of the usage of connection-id for controlling connection lifetime: https://github.com/Stiffstream/restinio/blob/v.0.6.12/dev/sample/ip_blocker/main.cpp The `blocker_t` serves two roles: as an ip-blocker and as a connection-listener.

**Comment by ngrodzitski** [comment]
For the initial question I would say look at [notification facility](https://stiffstream.com/en/docs/restinio/0.6/responsebuilder.html#notificators). I've used it for a simple back-pressure but I think it can be used to track connection errors if write operation takes place, any way it would trigger you when the next chunk would be tried to be send.
