### ISSUE TITLE
How to include js or css file when using sendfile to serve webpage?

### ISSUE THREAD

**Issue by faizol** [Stiffstream/restinio#150]
Hi,
 Referring to this https://github.com/Stiffstream/restinio/issues/43;
 How can I include the linked js or css file with the sent html file? The file(s) won't linked if I just send a html file, but it only display texts of the corresponding js or css file if I add the header and use append_body method. 

This is what I tried but failed;
`    .append_header( restinio::http_field::content_type, "application/javascript; charset=utf-8" )
    .set_body(restinio::sendfile( "./script.js"))
    .append_header( restinio::http_field::content_type, "text/css; charset=utf-8" )
    .append_body(restinio::sendfile( "./styles.css"))
    .append_header( restinio::http_field::content_type, "text/html; charset=utf-8" )
    .append_body(restinio::sendfile( "./page.html"))
    .done();` 

Any pointers on the right way to get this done? 

 Thank you.

**Comment by eao197** [comment]
Hi! As far as I understand the logic of HTTP/1.1, you can't return all necessary files to a client in one response. Instead, you get a single request first (something like `GET /index.html`) and send the content of `index.html` in the response. Your `index.html` has references to `script.js` and `styles.css`. The browser sees those references and makes two new separate requests to your server: one for `script.js` and another for `styles.css` (those requests can come one after another inside a single connection or can be sent in parallel in separate connections to your server).

So instead of concatenating all your files into one response you have to handle several incoming requests from a client and send just one file back for one request.

**Comment by faizol** [comment]
Thanks. That solved the problem.
